// <auto-generated />
using System;
using LanguageSchoolERP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LanguageSchoolERP.Data.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20260219233837_SplitStudentData")]
    partial class SplitStudentData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LanguageSchoolERP.Core.Models.AcademicPeriod", b =>
                {
                    b.Property<Guid>("AcademicPeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AcademicPeriodId");

                    b.ToTable("AcademicPeriods");
                });

            modelBuilder.Entity("LanguageSchoolERP.Core.Models.Contract", b =>
                {
                    b.Property<Guid>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContractTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocxPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PdfPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ContractId");

                    b.HasIndex("ContractTemplateId");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("StudentId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("LanguageSchoolERP.Core.Models.ContractTemplate", b =>
                {
                    b.Property<Guid>("ContractTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BranchKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TemplateRelativePath")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("ContractTemplateId");

                    b.ToTable("ContractTemplates");
                });

            modelBuilder.Entity("LanguageSchoolERP.Core.Models.Enrollment", b =>
                {
                    b.Property<Guid>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AcademicPeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AgreementTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BooksAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DownPayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("HasStudyLab")
                        .HasColumnType("bit");

                    b.Property<bool>("HasTransportation")
                        .HasColumnType("bit");

                    b.Property<bool>("IncludesStudyLab")
                        .HasColumnType("bit");

                    b.Property<bool>("IncludesTransportation")
                        .HasColumnType("bit");

                    b.Property<int>("InstallmentCount")
                        .HasColumnType("int");

                    b.Property<int>("InstallmentDayOfMonth")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InstallmentStartMonth")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsStopped")
                        .HasColumnType("bit");

                    b.Property<string>("LevelOrClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProgramId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StopReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("StoppedAmountWaived")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("StoppedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("StudyLabMonthlyFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("StudyLabMonthlyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TransportationMonthlyFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TransportationMonthlyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("AcademicPeriodId");

                    b.HasIndex("ProgramId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("LanguageSchoolERP.Core.Models.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Method")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PaymentId");

                    b.HasIndex("EnrollmentId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("LanguageSchoolERP.Core.Models.Receipt", b =>
                {
                    b.Property<Guid>("ReceiptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PdfPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceiptNumber")
                        .HasColumnType("int");

                    b.Property<string>("VoidReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Voided")
                        .HasColumnType("bit");

                    b.HasKey("ReceiptId");

                    b.HasIndex("PaymentId");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("LanguageSchoolERP.Core.Models.ReceiptCounter", b =>
                {
                    b.Property<int>("ReceiptCounterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReceiptCounterId"));

                    b.Property<Guid>("AcademicPeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NextReceiptNumber")
                        .HasColumnType("int");

                    b.HasKey("ReceiptCounterId");

                    b.HasIndex("AcademicPeriodId")
                        .IsUnique();

                    b.ToTable("ReceiptCounters");
                });

            modelBuilder.Entity("LanguageSchoolERP.Core.Models.Student", b =>
                {
                    b.Property<Guid>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Discontinued")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherLandline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherMobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Landline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherLandline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherMobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NonCollectable")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PreferredEmailSource")
                        .HasColumnType("int");

                    b.Property<int>("PreferredLandlineSource")
                        .HasColumnType("int");

                    b.Property<int>("PreferredPhoneSource")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("LanguageSchoolERP.Core.Models.StudyProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("HasBooks")
                        .HasColumnType("bit");

                    b.Property<bool>("HasStudyLab")
                        .HasColumnType("bit");

                    b.Property<bool>("HasTransport")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Programs", (string)null);
                });

            modelBuilder.Entity("LanguageSchoolERP.Core.Models.Contract", b =>
                {
                    b.HasOne("LanguageSchoolERP.Core.Models.ContractTemplate", "ContractTemplate")
                        .WithMany("Contracts")
                        .HasForeignKey("ContractTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LanguageSchoolERP.Core.Models.Enrollment", "Enrollment")
                        .WithMany("Contracts")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LanguageSchoolERP.Core.Models.Student", "Student")
                        .WithMany("Contracts")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ContractTemplate");

                    b.Navigation("Enrollment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LanguageSchoolERP.Core.Models.Enrollment", b =>
                {
                    b.HasOne("LanguageSchoolERP.Core.Models.AcademicPeriod", "AcademicPeriod")
                        .WithMany()
                        .HasForeignKey("AcademicPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LanguageSchoolERP.Core.Models.StudyProgram", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LanguageSchoolERP.Core.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicPeriod");

                    b.Navigation("Program");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LanguageSchoolERP.Core.Models.Payment", b =>
                {
                    b.HasOne("LanguageSchoolERP.Core.Models.Enrollment", "Enrollment")
                        .WithMany("Payments")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("LanguageSchoolERP.Core.Models.Receipt", b =>
                {
                    b.HasOne("LanguageSchoolERP.Core.Models.Payment", "Payment")
                        .WithMany("Receipts")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("LanguageSchoolERP.Core.Models.ReceiptCounter", b =>
                {
                    b.HasOne("LanguageSchoolERP.Core.Models.AcademicPeriod", "AcademicPeriod")
                        .WithMany()
                        .HasForeignKey("AcademicPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicPeriod");
                });

            modelBuilder.Entity("LanguageSchoolERP.Core.Models.ContractTemplate", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("LanguageSchoolERP.Core.Models.Enrollment", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("LanguageSchoolERP.Core.Models.Payment", b =>
                {
                    b.Navigation("Receipts");
                });

            modelBuilder.Entity("LanguageSchoolERP.Core.Models.Student", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
